### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by shadowzoom** [Frayo44/Bypass-Snapchat-SSL-Certificate-Pinning#3]
Im getting in output:
"C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\python.exe" frida_spawn.py burp.cer
pid: 21764
[*] Intercepting ...
Traceback (most recent call last):
  File "frida_spawn.py", line 33, in <module>
    script.post({'type': 'input', 'payload': file.read()})
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 758: character maps to <undefined>

Any help please?

**Comment by tomer8007** [comment]
<del>This sounds to me like you're using python 3 even though this script is built to be executed with python 2. Do you get the same output with python 2?</del>

a better idea: Is your certificate indeed in `PEM` format? Otherwise how come you have `\x98` in the file? It should be mostly base64.
